import { Scenario, Specialty } from './types';

// ===== SCENARIO DATABASE =====

export const SCENARIOS: Record<Specialty, Scenario[]> = {
    cardiology: [
        {
            id: 'card-001',
            specialty: 'cardiology',
            title: "O'tkir Miokard Infarkti (STEMI)",
            description: "55 yoshli erkak bemor ko'krak og'rig'i bilan tez yordamga keldi. EKG da ST elevatsiyasi aniqlandi.",
            difficulty: 'Medium',
            initial_presentation: "55 yoshli erkak bemor 2 soat oldin boshlangan kuchli ko'krak og'rig'i bilan tez yordam bo'limiga keldi. Og'riq chap yelkaga tarqalmoqda. Bemor terlagan, rangi oqargan. EKG: V1-V4 da ST segmenti elevatsiyasi. Troponin I: 2.5 ng/ml (normal <0.04).",
            initial_stats: { hr: 110, bp: '90/60', spo2: 94, rr: 22, temp: 36.8 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_chest', skin_color: 'pale' },
            expected_actions: ['Aspirin 325mg PO', 'Heparin IV', 'Clopidogrel', 'Morphine', 'Nitroglycerin', 'PCI/Angiography'],
            time_limit_minutes: 90,
        },
        {
            id: 'card-002',
            specialty: 'cardiology',
            title: "Atrial Fibrillyatsiya",
            description: "68 yoshli ayol bemor yurak urishining tartibsizligi va bosh aylanishi bilan keldi.",
            difficulty: 'Easy',
            initial_presentation: "68 yoshli ayol bemor 6 soat davom etgan yurak urishining tartibsizligi, bosh aylanishi va nafas qisilishi bilan keldi. Anamnezda gipertoniya. EKG: Atrial fibrillyatsiya, ventrikulyar rate 148/min.",
            initial_stats: { hr: 148, bp: '150/95', spo2: 96, rr: 20, temp: 36.6 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_chest', skin_color: 'flushed' },
            expected_actions: ['Metoprolol IV', 'Diltiazem', 'Antikoagulyant', 'Amiodarone'],
            time_limit_minutes: 60,
        },
        {
            id: 'card-003',
            specialty: 'cardiology',
            title: "Gipertonik Kriz",
            description: "72 yoshli erkak bemor bosh og'rig'i va ko'rish xiralashishi bilan keldi. AQB: 220/130.",
            difficulty: 'Hard',
            initial_presentation: "72 yoshli erkak bemor kuchli bosh og'rig'i, ko'rish xiralashishi va ko'krak og'rig'i bilan tez yordamga keldi. Anamnezda 15 yillik gipertoniya, dorilarini 1 hafta oldin o'zi tashlagan. AQB: 220/130 mmHg. Fundoskopiyada papilledema.",
            initial_stats: { hr: 95, bp: '220/130', spo2: 97, rr: 18, temp: 37.0 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_face', skin_color: 'flushed' },
            expected_actions: ['Nitroprusside IV', 'Labetalol IV', 'Furosemide', 'Monitoring'],
            time_limit_minutes: 120,
        },
    ],
    neurology: [
        {
            id: 'neuro-001',
            specialty: 'neurology',
            title: "Ishemik Insult (Stroke)",
            description: "62 yoshli erkak bemor to'satdan chap tomon falajlik bilan keldi.",
            difficulty: 'Hard',
            initial_presentation: "62 yoshli erkak bemor 1.5 soat oldin to'satdan chap qo'l va oyoqda kuchsizlik, nutq buzilishi (afaziya) paydo bo'lgan. NIHSS bali: 14. CT bosh miya: o'ng o'rta miya arteriyasi hududida o'tkir ishemik o'zgarishlar.",
            initial_stats: { hr: 88, bp: '170/100', spo2: 96, rr: 16, temp: 36.9, gcs: 12 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_face', skin_color: 'normal' },
            expected_actions: ['tPA (Alteplase)', 'Aspirin', 'AQB boshqarish', 'CT angiografiya'],
            time_limit_minutes: 60,
        },
        {
            id: 'neuro-002',
            specialty: 'neurology',
            title: "Epileptik Status",
            description: "28 yoshli ayol bemor 15 daqiqadan ortiq davom etgan tutqanoq holati bilan keldi.",
            difficulty: 'Hard',
            initial_presentation: "28 yoshli ayol bemor 15 daqiqadan ortiq davom etayotgan generalizatsiyalashgan tonik-klonik tutqanoq holati bilan tez yordamga olib kelindi. Anamnezda epilepsiya, oxirgi 3 kun dorilarini ichmagan.",
            initial_stats: { hr: 130, bp: '160/95', spo2: 88, rr: 28, temp: 38.5, gcs: 3 },
            initial_visual: { spline_state: 'Seizure', camera_angle: 'full_body', skin_color: 'cyanotic' },
            expected_actions: ['Diazepam IV', 'Lorazepam IV', 'Phenytoin IV', 'Kislorod', 'Airway management'],
            time_limit_minutes: 30,
        },
    ],
    pulmonology: [
        {
            id: 'pulmo-001',
            specialty: 'pulmonology',
            title: "Og'ir Bronxial Astma Xuruji",
            description: "35 yoshli erkak bemor og'ir nafas qisilishi bilan tez yordamga keldi.",
            difficulty: 'Medium',
            initial_presentation: "35 yoshli erkak bemor 3 soat davom etayotgan og'ir nafas qisilishi, xirillash va yo'tal bilan keldi. 3 marta salbutamol inhaler ishlatgan, lekin yaxshilanmagan. Nafas olishda yordamchi muskullardan foydalanmoqda. O'pkada bilateral xirillash eshitilmoqda.",
            initial_stats: { hr: 120, bp: '140/85', spo2: 89, rr: 32, temp: 37.2 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_chest', skin_color: 'cyanotic' },
            expected_actions: ['Salbutamol nebulizer', 'Ipratropium bromide', 'Prednizolon IV', 'Kislorod', 'MgSO4 IV'],
            time_limit_minutes: 45,
        },
        {
            id: 'pulmo-002',
            specialty: 'pulmonology',
            title: "Pnevmotoraks",
            description: "22 yoshli yigit to'satdan nafas qisilishi va ko'krak og'rig'i bilan keldi.",
            difficulty: 'Medium',
            initial_presentation: "22 yoshli yigit 1 soat oldin to'satdan boshlangan o'ng tomonlama ko'krak og'rig'i va nafas qisilishi bilan keldi. Oriq, uzun bo'yli. O'ng tomondan nafas tovushlari keskin pasaygan. Rentgenda o'ng tomonlama 40% pnevmotoraks.",
            initial_stats: { hr: 115, bp: '120/75', spo2: 91, rr: 26, temp: 36.7 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_chest', skin_color: 'pale' },
            expected_actions: ['Kislorod', 'Torakosentez', 'Drenaj qo\'yish', 'Og\'riq qoldirish'],
            time_limit_minutes: 60,
        },
    ],
    emergency: [
        {
            id: 'emrg-001',
            specialty: 'emergency',
            title: "Anafilaktik Shok",
            description: "30 yoshli ayol bemor ari chaqqandan so'ng og'ir allergik reaktsiya bilan keldi.",
            difficulty: 'Hard',
            initial_presentation: "30 yoshli ayol bemor 20 daqiqa oldin ari chaqqandan keyin nafas qisilishi, yuzining shishishi, butun tanada qichishma va bosh aylanishi bilan tez yordamga keldi. Ovozi xirillamoqda, lablar shishgan. AQB tushgan.",
            initial_stats: { hr: 135, bp: '75/40', spo2: 87, rr: 30, temp: 37.1 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_face', skin_color: 'flushed' },
            expected_actions: ['Adrenalin 0.5mg IM', 'Kislorod', 'IV suyuqlik', 'Difenhidramin', 'Deksametazon', 'Intubatsiya tayyor'],
            time_limit_minutes: 15,
        },
        {
            id: 'emrg-002',
            specialty: 'emergency',
            title: "Politravma",
            description: "Avtohalokada jarohat olgan 40 yoshli erkak bemor.",
            difficulty: 'Hard',
            initial_presentation: "40 yoshli erkak bemor avtohalokadan keyin tez yordam bilan olib kelindi. Hushsiz holat, bosh va ko'krak qafasi jarohatlari. Chap sondan qon ketmoqda. GCS: 8. Tez yordam jamoasi bo'yin fiksatori qo'ygan.",
            initial_stats: { hr: 140, bp: '80/50', spo2: 85, rr: 8, temp: 35.5, gcs: 8 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'full_body', skin_color: 'pale' },
            expected_actions: ['ABCDE yondashuv', 'Intubatsiya', 'IV suyuqlik', 'Qon preparatlari', 'CT', 'Jarrohlik konsultatsiya'],
            time_limit_minutes: 30,
        },
    ],
    pediatrics: [
        {
            id: 'ped-001',
            specialty: 'pediatrics',
            title: "Neonatal Sepsis",
            description: "3 kunlik yangi tug'ilgan chaqaloq harorat ko'tarilishi va letargiya bilan keldi.",
            difficulty: 'Medium',
            initial_presentation: "3 kunlik yangi tug'ilgan chaqaloq 38.8°C harorat, letargiya, yomon emishi va terining marmar rangga kirishi bilan olib kelindi. Ona anamnezida erta suvlanish. Laboratoriya: Leykositoz, CRP yuqori.",
            initial_stats: { hr: 180, bp: '55/30', spo2: 92, rr: 60, temp: 38.8 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'full_body', skin_color: 'pale' },
            expected_actions: ['Ampicillin IV', 'Gentamicin IV', 'IV suyuqlik', 'Qon kulturasi', 'LP'],
            time_limit_minutes: 60,
        },
    ],
    anesthesiology: [
        {
            id: 'anes-001',
            specialty: 'anesthesiology',
            title: "Qiyin Yo'l Boshqaruvi",
            description: "Umumiy anesteziya induksiyasida kutilmagan qiyin intubatsiya holati.",
            difficulty: 'Hard',
            initial_presentation: "45 yoshli, semirib ketgan (BMI 38) erkak bemor umumiy anesteziya induksiyasida intubatsiya qilish mumkin bo'lmadi. Mallampati IV sinf. Propofol va rokuroniy berildi. Ventilyatsiya mushkul. SpO2 tushmoqda.",
            initial_stats: { hr: 105, bp: '155/90', spo2: 82, rr: 0, temp: 36.5 },
            initial_visual: { spline_state: 'Pain', camera_angle: 'zoom_in_face', skin_color: 'cyanotic' },
            expected_actions: ['Video laringoskop', 'Supraglottik airway', 'Sugammdeks', 'Krikotirotomiya tayyor', 'Bag-mask ventilyatsiya'],
            time_limit_minutes: 10,
        },
    ],
};

export const SPECIALTIES: Record<Specialty, { name: string; nameUz: string; icon: string; description: string; color: string; gradient: string }> = {
    cardiology: {
        name: 'Cardiology',
        nameUz: 'Kardiologiya',
        icon: '🫀',
        description: "Yurak kasalliklari va qon aylanish tizimi simulyatsiyalari",
        color: '#ef476f',
        gradient: 'linear-gradient(135deg, #ef476f, #d63384)',
    },
    neurology: {
        name: 'Neurology',
        nameUz: 'Nevrologiya',
        icon: '🧠',
        description: "Nerv tizimi kasalliklari va bosh miya patologiyalari",
        color: '#7b68ee',
        gradient: 'linear-gradient(135deg, #7b68ee, #6366f1)',
    },
    pulmonology: {
        name: 'Pulmonology',
        nameUz: 'Pulmonologiya',
        icon: '🫁',
        description: "Nafas yo'llari va o'pka kasalliklari simulyatsiyalari",
        color: '#118ab2',
        gradient: 'linear-gradient(135deg, #118ab2, #06b6d4)',
    },
    emergency: {
        name: 'Emergency',
        nameUz: 'Tez Yordam',
        icon: '🚑',
        description: "Shoshilinch tibbiy holatlar va neotlojnaya pomosh'",
        color: '#ffd166',
        gradient: 'linear-gradient(135deg, #ffd166, #f59e0b)',
    },
    pediatrics: {
        name: 'Pediatrics',
        nameUz: 'Pediatriya',
        icon: '👶',
        description: "Bolalar kasalliklari va neonatal holatlar",
        color: '#06d6a0',
        gradient: 'linear-gradient(135deg, #06d6a0, #34d399)',
    },
    anesthesiology: {
        name: 'Anesthesiology',
        nameUz: 'Anesteziologiya',
        icon: '💉',
        description: "Anesteziya boshqaruvi va reanimatsiya holatlari",
        color: '#73d2de',
        gradient: 'linear-gradient(135deg, #73d2de, #67e8f9)',
    },
};
